<template>
	<div class="footerList">
		<div class="footer-link clearfix">
			<div class="footer-column">
				<dl>
					<dt>用户帮助</dt>
					<dd>
						<a
							rel="nofollow"
							href="http://www.meituan.com/help/selfservice"
							target="_blank"
							>申请退款</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="http://www.meituan.com/help/faq"
							target="_blank"
							>常见问题</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://rules-center.meituan.com/rules-detail/4"
							target="_blank"
							>用户协议</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://rules-center.meituan.com/rules-detail/2"
							target="_blank"
							>隐私政策</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="http://www.meituan.com/about/anticheat"
							target="_blank"
							>反诈骗公告</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://rules-center.meituan.com/customer-rights"
							target="_blank"
							>消费者权益保障</a
						>
					</dd>
				</dl>
				<dl>
					<dt>美团服务</dt>
					<dd>
						<a href="http://waimai.meituan.com/" target="_blank">美团外卖</a>
					</dd>
					<dd>
						<a href="http://hotel.meituan.com/" target="_blank">美团酒店</a>
					</dd>
					<dd><a href="http://maoyan.com/" target="_blank">猫眼电影</a></dd>
					<dd>
						<a href="https://peisong.meituan.com/" target="_blank">美团配送</a>
					</dd>
					<dd><a href="https://www.mtyun.com/" target="_blank">美团云</a></dd>
					<dd>
						<a href="http://www.dianping.com/" target="_blank">大众点评</a>
					</dd>
					<dd>
						<a href="https://minsu.meituan.com/" target="_blank">美团民宿</a>
					</dd>
					<dd>
						<a href="https://mad.meituan.com" target="_blank">无人配送</a>
					</dd>
				</dl>
			</div>
			<div class="footer-column">
				<dl>
					<dt>商家合作</dt>
					<dd>
						<a
							rel="nofollow"
							href="http://b.meituan.com/canyin/PC"
							target="_blank"
							>美团餐饮商户中心</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://ecom.meituan.com/bizsettle/settle?utm_source=mt_C_my"
							target="_blank"
							>美食商家入驻(非外卖)</a
						>
					</dd>
					<dd>
						<a href="https://kd.meituan.com/" target="_blank"
							>美团外卖开店申请</a
						>
					</dd>
					<dd>
						<a
							href="http://shouyin.meituan.com?utm_source=inner&amp;utm_medium=mtpc"
							target="_blank"
							>美团收银官网</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="http://page.peisong.meituan.com/apply/join"
							target="_blank"
							>外卖配送加盟申请</a
						>
					</dd>
					<dd>
						<a href="https://xue.meituan.com/?from=mtpc" target="_blank"
							>美团餐饮学院</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://ruzhu.meituan.com/settle/hotel/propaganda.html"
							target="_blank"
							>酒店商家入驻</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://ruzhu.meituan.com/settle/trip/pc.html"
							target="_blank"
							>境内度假商家入驻</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://e.dianping.com/claimcpc/page/index?source=mt"
							target="_blank"
							>综合商家入驻</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://minsu.meituan.com/about/"
							target="_blank"
							>美团民宿房东商家入驻</a
						>
					</dd>
					<dd>
						<a
							href="http://pc.meituan.com/?activity_code=mtpcdb"
							target="_blank"
							>商家开票申请</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://h5.youzan.com/v2/feature/nALm22bkFF?dc_ps=2039811416638097413.200001"
							target="_blank"
							>美团智能收银机</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://developer.meituan.com/?from=mtpcsw"
							target="_blank"
							>美团餐饮开放平台</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://recommend-zc.meituan.com/opportunity?channel=1"
							target="_blank"
							>美团收单</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://paidui.meituan.com/?activity_code=167_00038050"
							target="_blank"
							>免费使用美团排队</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://i.meituan.com/awp/hfe/block/6c4bec785dce/11188/index.html"
							target="_blank"
							>快驴进货商家合作</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://shangou.meituan.com/joinin"
							target="_blank"
							>美团闪购商家入驻</a
						>
					</dd>
				</dl>
			</div>
			<div class="footer-column">
				<dl>
					<dt>代理商加盟</dt>
					<dd>
						<a
							rel="nofollow"
							href="https://mfe.waimai.meituan.com/mfepro/client-h5/#/login"
							target="_blank"
							>美团外卖代理商招募</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://daili.meituan.com/?comeFrom=mtwebBusinesscoopd"
							target="_blank"
							>到店餐饮代理商招募</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="http://www.dianping.com/apollo/agent/index?source=mtpcd"
							target="_blank"
							>非餐饮代理商招募</a
						>
					</dd>
					<dd>
						<a rel="nofollow" href="http://union.meituan.com/" target="_blank"
							>美团联盟</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://wenjuan.meituan.com/survey/4332711"
							target="_blank"
							>美团收银招募线上分销商</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://agent.meituan.com/zhaoshang?partnerSource=3"
							target="_blank"
							>美团5S服务商招募</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://zf.meituan.com?partnerSource=3"
							target="_blank"
							>美团收单渠道代理商招募</a
						>
					</dd>
				</dl>
				<dl>
					<dt>美团规则</dt>
					<dd>
						<a
							rel="nofollow"
							href="https://rules-center.meituan.com/"
							target="_blank"
							>规则中心</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://rules-center.meituan.com/rules"
							target="_blank"
							>规则目录</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://rules-center.meituan.com/advices"
							target="_blank"
							>规则评议院</a
						>
					</dd>
				</dl>
			</div>
			<div class="footer-column">
				<dl>
					<dt>关注美团</dt>
					<dd>
						<a rel="nofollow" href="http://weibo.com/meituan" target="_blank"
							>美团新浪微博</a
						>
					</dd>
				</dl>
				<dl>
					<dt>公司信息</dt>
					<dd>
						<a rel="nofollow" href="https://about.meituan.com/" target="_blank"
							>关于我们</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://about.meituan.com/investor.html"
							target="_blank"
							>投资者关系</a
						>
					</dd>
					<dd>
						<a rel="nofollow" href="http://zhaopin.meituan.com/" target="_blank"
							>加入我们</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://dpapp-appeal.meituan.com/#/shopCreditRegulationPC"
							target="_blank"
							>商户诚信公约及管理办法</a
						>
					</dd>
					<dd>
						<a
							rel="nofollow"
							href="https://i.meituan.com/awp/ffe/insurance-website/index.html#/"
							target="_blank"
							>保险经纪资质</a
						>
					</dd>
				</dl>
				<dl>
					<dt>廉正举报</dt>
					<dd>
						<a
							rel="nofollow"
							href="https://jubao.meituan.com/app/home?source=1"
							target="_self"
							>廉正举报平台</a
						>
					</dd>
				</dl>
				<dl>
					<dt>知识产权</dt>
					<dd>
						<a
							rel="nofollow"
							href="https://ipr.meituan.com?source=1"
							target="_blank"
							>知识产权维权平台</a
						>
					</dd>
				</dl>
			</div>
			<div class="footer-column">
				<dl>
					<dt>消费者服务热线</dt>
					<dd>
						外卖消费者：<a rel="nofollow" href="tel:10109777" target="_blank"
							>10109777</a
						>
					</dd>
					<dd>
						猫眼消费者：<a rel="nofollow" href="tel:10105335" target="_blank"
							>10105335</a
						>
					</dd>
					<dd>
						其他消费者：<a rel="nofollow" href="tel:10107888" target="_blank"
							>10107888</a
						>
					</dd>
				</dl>
				<dl>
					<dt>商家服务热线</dt>
					<dd>
						外卖&amp;餐饮商家：<a
							rel="nofollow"
							href="tel:10105557"
							target="_blank"
							>10105557</a
						>
					</dd>
					<dd>
						休闲娱乐、丽人、ktv、教育、结婚、亲子、家装等商家：<a
							rel="nofollow"
							href="tel:10100107"
							target="_blank"
							>10100107</a
						>
					</dd>
				</dl>
				<dl>
					<dt>投诉举报专区</dt>
					<dd>
						违法和不良信息举报电话：<a
							rel="nofollow"
							href="tel:4006018900"
							target="_blank"
							>4006018900</a
						>
					</dd>
					<dd>
						举报邮箱：<a
							rel="nofollow"
							href="mailto:tousujubao@meituan.com"
							target="_self"
							>tousujubao@meituan.com</a
						>
					</dd>
					<dd>
						<a rel="nofollow" href="https://www.12377.cn/" target="_blank"
							>网上有害信息举报</a
						>
					</dd>
				</dl>
				<dl>
					<dt>
						<a
							rel="nofollow"
							href="https://ecom.meituan.com/bizsettle/settle/merchantsSettle"
							target="_blank"
							>商家自助入驻美团入口</a
						>
					</dt>
				</dl>
				<dl>
					<dt>
						<a
							rel="nofollow"
							href="https://isp.meituan.com/signup"
							target="_blank"
							>供应商注册入口</a
						>
					</dt>
				</dl>
			</div>
		</div>
	</div>
</template>
<style scoped>
 .footer-link {
   font-size: 14px;
    padding: 40px 45px;
    border-top: 1px solid #E5E5E5;
    border-bottom: 1px solid #E5E5E5;
}
 .footer-link {
   overflow: hidden;
 }
 .footer-link .footer-column {
    width: 20%;
    float: left;
}
 .footer-link dl {
    padding-bottom: 20px;
    color: #666;
}
 .footer-link dl dd {
  line-height: 30px;
}
 .footer-link dl dd a {
   color: #777 ;
 }
 .footer-link dl dd a:hover {
   color:#111
 }
</style>